FROM allwares/centos-httpd-php:2.2 
WORKDIR /var/www/html/

COPY --from=allwares/mag-base-zip:2.2 /magento.zip ./
COPY httpd.conf /etc/httpd/conf/
COPY php.ini /etc/

RUN unzip ./magento.zip -d ./ \
 		&& rm -f ./magento.zip 


RUN chown -R apache:apache /var/www/html/ \
		&& chmod -R 775 /var/www/html/

