FROM allwares/centos-httpd-php:latest 
WORKDIR /var/www/html/

COPY --from=allwares/mag-base-zip:latest /magento.zip ./
RUN unzip ./magento.zip -d ./

RUN find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +
RUN find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +
RUN chmod u+x bin/magento

RUN rm -f ./magento.zip
