FROM composer:latest AS magento-2.2-composer
WORKDIR /magento
COPY *.json ./

RUN composer install --ignore-platform-reqs

FROM alpine AS magento-2.2-files

RUN apk update
RUN apk add zip

WORKDIR /magento
COPY --from=magento-2.2-composer /magento ./
RUN zip -r /magento.zip ./

FROM alpine AS magento-2.2-zip
COPY --from=magento-2.2-files /magento.zip /

